services:
    postgres:
        container_name: pizzashop-pg
        image: postgres:16.0-alpine3.18
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=pizza_chief
            - POSTGRES_PASSWORD=cowabunga
            - POSTGRES_DB=pizzashop-db
        volumes:
            - pizzashop_api_pg:/database/postgres

volumes:
    pizzashop_api_pg:
